import { COMMAND_IDS, type Command } from '@/features/command/core'

export const generalCommands: Command[] = [
	{
		id: COMMAND_IDS.openCommandMenu,
		title: '打开命令菜单',
		category: 'general',
		scope: ['global'],
		description: '打开 StoneFlow 的全局命令入口。',
		keywords: ['command', 'cmdk', '命令'],
		// 静态命令只承载元数据；Shell 运行时会通过 adapter 绑定真实动作。
		run: () => {},
	},
	{
		id: COMMAND_IDS.openSearch,
		title: '打开搜索',
		category: 'general',
		scope: ['global'],
		description: '聚焦全局搜索框。',
		keywords: ['search', 'find', '搜索'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.close,
		title: '关闭当前层级',
		category: 'general',
		scope: ['global'],
		description: '关闭当前最高层级的弹窗、菜单或清空选择。',
		keywords: ['escape', 'close', '关闭'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.selectionDeleteByRoute,
		title: '删除选中项',
		category: 'general',
		scope: ['global'],
		description: '删除当前选中的任务、项目、归档或回收站条目。',
		keywords: ['delete', 'trash', '删除', '回收站', '永久删除'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.saveOrSubmit,
		title: '保存或提交',
		category: 'general',
		scope: ['global'],
		description: '保存当前编辑或提交当前表单。',
		keywords: ['save', 'submit', '保存', '提交'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.submitAndContinue,
		title: '提交并创建下一条',
		category: 'general',
		scope: ['global'],
		description: '提交当前表单，并继续保留元数据创建下一条。',
		keywords: ['submit', 'continue', '提交', '下一条', '连续创建'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.submitAndOpen,
		title: '提交并打开',
		category: 'general',
		scope: ['global'],
		description: '提交当前表单，并打开刚创建的内容。',
		keywords: ['submit', 'open', '提交', '打开'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.openShortcutHelp,
		title: '查看快捷键',
		category: 'general',
		scope: ['global'],
		description: '打开快捷键帮助。',
		keywords: ['shortcut', 'help', '快捷键'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.openSettings,
		title: '打开设置',
		category: 'general',
		scope: ['global'],
		description: '打开设置页面。',
		keywords: ['settings', '设置'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.goBack,
		title: '后退',
		category: 'general',
		scope: ['global'],
		description: '回到上一个访问位置。',
		keywords: ['back', 'history', '后退'],
		run: () => {},
	},
	{
		id: COMMAND_IDS.goForward,
		title: '前进',
		category: 'general',
		scope: ['global'],
		description: '前进到下一个访问位置。',
		keywords: ['forward', 'history', '前进'],
		run: () => {},
	},
]
