import { COMMAND_IDS } from '@/features/command/core'

import type { Keybinding } from './keybinding.types'

export const DEFAULT_KEYBINDINGS: Keybinding[] = [
	{
		commandId: COMMAND_IDS.openCommandMenu,
		sequence: [{ key: 'k', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openCommandMenu,
		sequence: [{ key: 'k', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openSearch,
		sequence: [{ key: '/' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.close,
		sequence: [{ key: 'Escape' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.layoutToggleSidebar,
		sequence: [{ key: '[' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.layoutTogglePreview,
		sequence: [{ key: ']' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.saveOrSubmit,
		sequence: [{ key: 'Enter', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.saveOrSubmit,
		sequence: [{ key: 'Enter', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.submitAndContinue,
		sequence: [{ key: 'Enter', meta: true, shift: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.submitAndContinue,
		sequence: [{ key: 'Enter', ctrl: true, shift: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.submitAndOpen,
		sequence: [{ key: 'Enter', meta: true, alt: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.submitAndOpen,
		sequence: [{ key: 'Enter', ctrl: true, alt: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openShortcutHelp,
		sequence: [{ key: '/', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openSettings,
		sequence: [{ key: ',', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openSettings,
		sequence: [{ key: ',', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.goBack,
		sequence: [{ key: '[', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.goBack,
		sequence: [{ key: '[', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.goForward,
		sequence: [{ key: ']', meta: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.goForward,
		sequence: [{ key: ']', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.openShortcutHelp,
		sequence: [{ key: '/', ctrl: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: true,
	},
	{
		commandId: COMMAND_IDS.newQuickTask,
		sequence: [{ key: 'c' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.newFullTask,
		sequence: [{ key: 'n' }, { key: 't' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.newTaskInInbox,
		sequence: [{ key: 'n' }, { key: 'i' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.newProject,
		sequence: [{ key: 'n' }, { key: 'p' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.newView,
		sequence: [{ key: 'n' }, { key: 'v' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.openTask,
		sequence: [{ key: 'o' }, { key: 't' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.openProject,
		sequence: [{ key: 'o' }, { key: 'p' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.openView,
		sequence: [{ key: 'o' }, { key: 'v' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.openSpace,
		sequence: [{ key: 'o' }, { key: 's' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.openRecent,
		sequence: [{ key: 'o' }, { key: 'r' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskChangePlacement,
		sequence: [{ key: 'p', shift: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goInbox,
		sequence: [{ key: 'g' }, { key: 'i' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goAllTasks,
		sequence: [{ key: 'g' }, { key: 't' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goToday,
		sequence: [{ key: 'g' }, { key: 'd' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goUpcoming,
		sequence: [{ key: 'g' }, { key: 'u' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goFocus,
		sequence: [{ key: 'g' }, { key: 'f' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goViews,
		sequence: [{ key: 'g' }, { key: 'v' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goProjects,
		sequence: [{ key: 'g' }, { key: 'p' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goArchive,
		sequence: [{ key: 'g' }, { key: 'a' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goTrash,
		sequence: [{ key: 'g' }, { key: 'x' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goSettings,
		sequence: [{ key: 'g' }, { key: 's' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.goRecent,
		sequence: [{ key: 'g' }, { key: 'r' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterByPriority,
		sequence: [{ key: 'f' }, { key: 'p' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterByStatus,
		sequence: [{ key: 'f' }, { key: 's' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterByDate,
		sequence: [{ key: 'f' }, { key: 'd' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterByProject,
		sequence: [{ key: 'f' }, { key: 'j' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterToggleCompleted,
		sequence: [{ key: 'f' }, { key: 'c' }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.filterClearAll,
		sequence: [{ key: 'f', shift: true }],
		scope: 'global',
		preventDefault: true,
		allowInEditable: false,
	},
]
