export const COLLECTION_ROW_HEIGHT = 44
export const COLLECTION_SECTION_HEADER_HEIGHT = 36
export const COLLECTION_ITEM_GAP = 2
export const COLLECTION_ROW_STRIDE = COLLECTION_ROW_HEIGHT + COLLECTION_ITEM_GAP
export const COLLECTION_SECTION_HEADER_STRIDE =
	COLLECTION_SECTION_HEADER_HEIGHT + COLLECTION_ITEM_GAP
