[package]
name = "stoneflow-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_domain"
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
