import { COMMAND_IDS, type Keybinding } from '@/features/command/contract'

export const TASK_ROW_SHORTCUT_BINDINGS: readonly Keybinding[] = [
	{
		commandId: COMMAND_IDS.taskComplete,
		sequence: [{ key: 'w' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskSelect,
		sequence: [{ key: 'x' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskPeek,
		sequence: [{ key: 'Space' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskOpenDetail,
		sequence: [{ key: 'Enter' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskArchive,
		sequence: [{ key: 'a' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskDelete,
		sequence: [{ key: 'Delete' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskDelete,
		sequence: [{ key: 'Backspace', mod: true }],
		scope: 'row',
		display: 'alternative',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskSetPriority,
		sequence: [{ key: 'p' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskSetStatus,
		sequence: [{ key: 's' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskOpenDateMenu,
		sequence: [{ key: 'd' }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
	{
		commandId: COMMAND_IDS.taskChangePlacement,
		sequence: [{ key: 'p', shift: true }],
		scope: 'row',
		display: 'primary',
		preventDefault: true,
		allowInEditable: false,
	},
]
