[package]
name = "stoneflow-sync-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "stoneflow-sync-worker"
path = "src/main.rs"

[dependencies]
libsql.workspace = true
serde.workspace = true
serde_json.workspace = true
stoneflow-domain = { path = "../domain" }
thiserror.workspace = true
tokio.workspace = true
