[package]
name = "stoneflow-usecase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_usecase"
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
stoneflow-domain = { path = "../domain" }
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
