[package]
name = "stoneflow-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_runtime"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
log.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
stoneflow-domain = { path = "../domain" }
stoneflow-platform = { path = "../platform" }
stoneflow-schema = { path = "../schema" }
stoneflow-storage = { path = "../storage" }
stoneflow-usecase = { path = "../usecase" }
tauri = { workspace = true, features = ["macos-private-api", "tray-icon"] }
tauri-plugin-dialog.workspace = true
tauri-plugin-global-shortcut.workspace = true
tauri-plugin-log.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-single-instance.workspace = true
tauri-plugin-store.workspace = true
tauri-plugin-updater.workspace = true
tauri-plugin-window-state.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
stoneflow-test-support = { path = "../test-support" }
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", branch = "v2.1" }
