[package]
name = "stoneflow-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_testing"
path = "src/lib.rs"

[dependencies]
stoneflow-domain = { path = "../domain" }
stoneflow-migration = { path = "../migration" }
stoneflow-storage = { path = "../storage" }
stoneflow-usecase = { path = "../usecase" }
