[package]
name = "stoneflow-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_storage"
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true
serde_json.workspace = true
stoneflow-application = { path = "../application" }
stoneflow-domain = { path = "../domain" }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
stoneflow-test-support = { path = "../test-support" }
tokio.workspace = true
sea-orm.workspace = true

[features]
test-helpers = []
