/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuickCreateRouteImport } from './routes/quick-create'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllIndexRouteImport } from './routes/all.index'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as DebugActivityRouteImport } from './routes/debug.activity'
import { Route as AllViewsRouteImport } from './routes/all.views'
import { Route as AllTrashRouteImport } from './routes/all.trash'
import { Route as AllTasksRouteImport } from './routes/all.tasks'
import { Route as AllSettingsRouteImport } from './routes/all.settings'
import { Route as AllProjectsRouteImport } from './routes/all.projects'
import { Route as AllNoProjectRouteImport } from './routes/all.no-project'
import { Route as AllInboxRouteImport } from './routes/all.inbox'
import { Route as AllArchiveRouteImport } from './routes/all.archive'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces.$spaceId.index'
import { Route as SpacesSpaceIdViewsRouteImport } from './routes/spaces.$spaceId.views'
import { Route as SpacesSpaceIdTrashRouteImport } from './routes/spaces.$spaceId.trash'
import { Route as SpacesSpaceIdTasksRouteImport } from './routes/spaces.$spaceId.tasks'
import { Route as SpacesSpaceIdSettingsRouteImport } from './routes/spaces.$spaceId.settings'
import { Route as SpacesSpaceIdProjectsRouteImport } from './routes/spaces.$spaceId.projects'
import { Route as SpacesSpaceIdNoProjectRouteImport } from './routes/spaces.$spaceId.no-project'
import { Route as SpacesSpaceIdInboxRouteImport } from './routes/spaces.$spaceId.inbox'
import { Route as SpacesSpaceIdArchiveRouteImport } from './routes/spaces.$spaceId.archive'
import { Route as AllViewsViewIdRouteImport } from './routes/all.views.$viewId'
import { Route as AllProjectsProjectIdRouteImport } from './routes/all.projects.$projectId'
import { Route as SpacesSpaceIdViewsViewIdRouteImport } from './routes/spaces.$spaceId.views.$viewId'
import { Route as SpacesSpaceIdTasksTaskIdRouteImport } from './routes/spaces.$spaceId.tasks.$taskId'
import { Route as SpacesSpaceIdProjectsProjectIdRouteImport } from './routes/spaces.$spaceId.projects.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickCreateRoute = QuickCreateRouteImport.update({
  id: '/quick-create',
  path: '/quick-create',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllIndexRoute = AllIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AllRoute,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugActivityRoute = DebugActivityRouteImport.update({
  id: '/debug/activity',
  path: '/debug/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AllViewsRoute = AllViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AllRoute,
} as any)
const AllTrashRoute = AllTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AllRoute,
} as any)
const AllTasksRoute = AllTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AllRoute,
} as any)
const AllSettingsRoute = AllSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AllRoute,
} as any)
const AllProjectsRoute = AllProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AllRoute,
} as any)
const AllNoProjectRoute = AllNoProjectRouteImport.update({
  id: '/no-project',
  path: '/no-project',
  getParentRoute: () => AllRoute,
} as any)
const AllInboxRoute = AllInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AllRoute,
} as any)
const AllArchiveRoute = AllArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AllRoute,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdViewsRoute = SpacesSpaceIdViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdTrashRoute = SpacesSpaceIdTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdTasksRoute = SpacesSpaceIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdSettingsRoute = SpacesSpaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdProjectsRoute = SpacesSpaceIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdNoProjectRoute = SpacesSpaceIdNoProjectRouteImport.update({
  id: '/no-project',
  path: '/no-project',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdInboxRoute = SpacesSpaceIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdArchiveRoute = SpacesSpaceIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const AllViewsViewIdRoute = AllViewsViewIdRouteImport.update({
  id: '/$viewId',
  path: '/$viewId',
  getParentRoute: () => AllViewsRoute,
} as any)
const AllProjectsProjectIdRoute = AllProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AllProjectsRoute,
} as any)
const SpacesSpaceIdViewsViewIdRoute =
  SpacesSpaceIdViewsViewIdRouteImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => SpacesSpaceIdViewsRoute,
  } as any)
const SpacesSpaceIdTasksTaskIdRoute =
  SpacesSpaceIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => SpacesSpaceIdTasksRoute,
  } as any)
const SpacesSpaceIdProjectsProjectIdRoute =
  SpacesSpaceIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => SpacesSpaceIdProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRouteWithChildren
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/all/archive': typeof AllArchiveRoute
  '/all/inbox': typeof AllInboxRoute
  '/all/no-project': typeof AllNoProjectRoute
  '/all/projects': typeof AllProjectsRouteWithChildren
  '/all/settings': typeof AllSettingsRoute
  '/all/tasks': typeof AllTasksRoute
  '/all/trash': typeof AllTrashRoute
  '/all/views': typeof AllViewsRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/all/': typeof AllIndexRoute
  '/all/projects/$projectId': typeof AllProjectsProjectIdRoute
  '/all/views/$viewId': typeof AllViewsViewIdRoute
  '/spaces/$spaceId/archive': typeof SpacesSpaceIdArchiveRoute
  '/spaces/$spaceId/inbox': typeof SpacesSpaceIdInboxRoute
  '/spaces/$spaceId/no-project': typeof SpacesSpaceIdNoProjectRoute
  '/spaces/$spaceId/projects': typeof SpacesSpaceIdProjectsRouteWithChildren
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/spaces/$spaceId/tasks': typeof SpacesSpaceIdTasksRouteWithChildren
  '/spaces/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/spaces/$spaceId/views': typeof SpacesSpaceIdViewsRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/projects/$projectId': typeof SpacesSpaceIdProjectsProjectIdRoute
  '/spaces/$spaceId/tasks/$taskId': typeof SpacesSpaceIdTasksTaskIdRoute
  '/spaces/$spaceId/views/$viewId': typeof SpacesSpaceIdViewsViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/all/archive': typeof AllArchiveRoute
  '/all/inbox': typeof AllInboxRoute
  '/all/no-project': typeof AllNoProjectRoute
  '/all/projects': typeof AllProjectsRouteWithChildren
  '/all/settings': typeof AllSettingsRoute
  '/all/tasks': typeof AllTasksRoute
  '/all/trash': typeof AllTrashRoute
  '/all/views': typeof AllViewsRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/all': typeof AllIndexRoute
  '/all/projects/$projectId': typeof AllProjectsProjectIdRoute
  '/all/views/$viewId': typeof AllViewsViewIdRoute
  '/spaces/$spaceId/archive': typeof SpacesSpaceIdArchiveRoute
  '/spaces/$spaceId/inbox': typeof SpacesSpaceIdInboxRoute
  '/spaces/$spaceId/no-project': typeof SpacesSpaceIdNoProjectRoute
  '/spaces/$spaceId/projects': typeof SpacesSpaceIdProjectsRouteWithChildren
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/spaces/$spaceId/tasks': typeof SpacesSpaceIdTasksRouteWithChildren
  '/spaces/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/spaces/$spaceId/views': typeof SpacesSpaceIdViewsRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/projects/$projectId': typeof SpacesSpaceIdProjectsProjectIdRoute
  '/spaces/$spaceId/tasks/$taskId': typeof SpacesSpaceIdTasksTaskIdRoute
  '/spaces/$spaceId/views/$viewId': typeof SpacesSpaceIdViewsViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRouteWithChildren
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/all/archive': typeof AllArchiveRoute
  '/all/inbox': typeof AllInboxRoute
  '/all/no-project': typeof AllNoProjectRoute
  '/all/projects': typeof AllProjectsRouteWithChildren
  '/all/settings': typeof AllSettingsRoute
  '/all/tasks': typeof AllTasksRoute
  '/all/trash': typeof AllTrashRoute
  '/all/views': typeof AllViewsRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/all/': typeof AllIndexRoute
  '/all/projects/$projectId': typeof AllProjectsProjectIdRoute
  '/all/views/$viewId': typeof AllViewsViewIdRoute
  '/spaces/$spaceId/archive': typeof SpacesSpaceIdArchiveRoute
  '/spaces/$spaceId/inbox': typeof SpacesSpaceIdInboxRoute
  '/spaces/$spaceId/no-project': typeof SpacesSpaceIdNoProjectRoute
  '/spaces/$spaceId/projects': typeof SpacesSpaceIdProjectsRouteWithChildren
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/spaces/$spaceId/tasks': typeof SpacesSpaceIdTasksRouteWithChildren
  '/spaces/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/spaces/$spaceId/views': typeof SpacesSpaceIdViewsRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/projects/$projectId': typeof SpacesSpaceIdProjectsProjectIdRoute
  '/spaces/$spaceId/tasks/$taskId': typeof SpacesSpaceIdTasksTaskIdRoute
  '/spaces/$spaceId/views/$viewId': typeof SpacesSpaceIdViewsViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/quick-create'
    | '/settings'
    | '/all/archive'
    | '/all/inbox'
    | '/all/no-project'
    | '/all/projects'
    | '/all/settings'
    | '/all/tasks'
    | '/all/trash'
    | '/all/views'
    | '/debug/activity'
    | '/spaces/$spaceId'
    | '/all/'
    | '/all/projects/$projectId'
    | '/all/views/$viewId'
    | '/spaces/$spaceId/archive'
    | '/spaces/$spaceId/inbox'
    | '/spaces/$spaceId/no-project'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/settings'
    | '/spaces/$spaceId/tasks'
    | '/spaces/$spaceId/trash'
    | '/spaces/$spaceId/views'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/projects/$projectId'
    | '/spaces/$spaceId/tasks/$taskId'
    | '/spaces/$spaceId/views/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quick-create'
    | '/settings'
    | '/all/archive'
    | '/all/inbox'
    | '/all/no-project'
    | '/all/projects'
    | '/all/settings'
    | '/all/tasks'
    | '/all/trash'
    | '/all/views'
    | '/debug/activity'
    | '/all'
    | '/all/projects/$projectId'
    | '/all/views/$viewId'
    | '/spaces/$spaceId/archive'
    | '/spaces/$spaceId/inbox'
    | '/spaces/$spaceId/no-project'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/settings'
    | '/spaces/$spaceId/tasks'
    | '/spaces/$spaceId/trash'
    | '/spaces/$spaceId/views'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/projects/$projectId'
    | '/spaces/$spaceId/tasks/$taskId'
    | '/spaces/$spaceId/views/$viewId'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/quick-create'
    | '/settings'
    | '/all/archive'
    | '/all/inbox'
    | '/all/no-project'
    | '/all/projects'
    | '/all/settings'
    | '/all/tasks'
    | '/all/trash'
    | '/all/views'
    | '/debug/activity'
    | '/spaces/$spaceId'
    | '/all/'
    | '/all/projects/$projectId'
    | '/all/views/$viewId'
    | '/spaces/$spaceId/archive'
    | '/spaces/$spaceId/inbox'
    | '/spaces/$spaceId/no-project'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/settings'
    | '/spaces/$spaceId/tasks'
    | '/spaces/$spaceId/trash'
    | '/spaces/$spaceId/views'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/projects/$projectId'
    | '/spaces/$spaceId/tasks/$taskId'
    | '/spaces/$spaceId/views/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRouteWithChildren
  QuickCreateRoute: typeof QuickCreateRoute
  SettingsRoute: typeof SettingsRoute
  DebugActivityRoute: typeof DebugActivityRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-create': {
      id: '/quick-create'
      path: '/quick-create'
      fullPath: '/quick-create'
      preLoaderRoute: typeof QuickCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/': {
      id: '/all/'
      path: '/'
      fullPath: '/all/'
      preLoaderRoute: typeof AllIndexRouteImport
      parentRoute: typeof AllRoute
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/activity': {
      id: '/debug/activity'
      path: '/debug/activity'
      fullPath: '/debug/activity'
      preLoaderRoute: typeof DebugActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/views': {
      id: '/all/views'
      path: '/views'
      fullPath: '/all/views'
      preLoaderRoute: typeof AllViewsRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/trash': {
      id: '/all/trash'
      path: '/trash'
      fullPath: '/all/trash'
      preLoaderRoute: typeof AllTrashRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/tasks': {
      id: '/all/tasks'
      path: '/tasks'
      fullPath: '/all/tasks'
      preLoaderRoute: typeof AllTasksRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/settings': {
      id: '/all/settings'
      path: '/settings'
      fullPath: '/all/settings'
      preLoaderRoute: typeof AllSettingsRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/projects': {
      id: '/all/projects'
      path: '/projects'
      fullPath: '/all/projects'
      preLoaderRoute: typeof AllProjectsRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/no-project': {
      id: '/all/no-project'
      path: '/no-project'
      fullPath: '/all/no-project'
      preLoaderRoute: typeof AllNoProjectRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/inbox': {
      id: '/all/inbox'
      path: '/inbox'
      fullPath: '/all/inbox'
      preLoaderRoute: typeof AllInboxRouteImport
      parentRoute: typeof AllRoute
    }
    '/all/archive': {
      id: '/all/archive'
      path: '/archive'
      fullPath: '/all/archive'
      preLoaderRoute: typeof AllArchiveRouteImport
      parentRoute: typeof AllRoute
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/views': {
      id: '/spaces/$spaceId/views'
      path: '/views'
      fullPath: '/spaces/$spaceId/views'
      preLoaderRoute: typeof SpacesSpaceIdViewsRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/trash': {
      id: '/spaces/$spaceId/trash'
      path: '/trash'
      fullPath: '/spaces/$spaceId/trash'
      preLoaderRoute: typeof SpacesSpaceIdTrashRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/tasks': {
      id: '/spaces/$spaceId/tasks'
      path: '/tasks'
      fullPath: '/spaces/$spaceId/tasks'
      preLoaderRoute: typeof SpacesSpaceIdTasksRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/settings': {
      id: '/spaces/$spaceId/settings'
      path: '/settings'
      fullPath: '/spaces/$spaceId/settings'
      preLoaderRoute: typeof SpacesSpaceIdSettingsRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/projects': {
      id: '/spaces/$spaceId/projects'
      path: '/projects'
      fullPath: '/spaces/$spaceId/projects'
      preLoaderRoute: typeof SpacesSpaceIdProjectsRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/no-project': {
      id: '/spaces/$spaceId/no-project'
      path: '/no-project'
      fullPath: '/spaces/$spaceId/no-project'
      preLoaderRoute: typeof SpacesSpaceIdNoProjectRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/inbox': {
      id: '/spaces/$spaceId/inbox'
      path: '/inbox'
      fullPath: '/spaces/$spaceId/inbox'
      preLoaderRoute: typeof SpacesSpaceIdInboxRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/archive': {
      id: '/spaces/$spaceId/archive'
      path: '/archive'
      fullPath: '/spaces/$spaceId/archive'
      preLoaderRoute: typeof SpacesSpaceIdArchiveRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/all/views/$viewId': {
      id: '/all/views/$viewId'
      path: '/$viewId'
      fullPath: '/all/views/$viewId'
      preLoaderRoute: typeof AllViewsViewIdRouteImport
      parentRoute: typeof AllViewsRoute
    }
    '/all/projects/$projectId': {
      id: '/all/projects/$projectId'
      path: '/$projectId'
      fullPath: '/all/projects/$projectId'
      preLoaderRoute: typeof AllProjectsProjectIdRouteImport
      parentRoute: typeof AllProjectsRoute
    }
    '/spaces/$spaceId/views/$viewId': {
      id: '/spaces/$spaceId/views/$viewId'
      path: '/$viewId'
      fullPath: '/spaces/$spaceId/views/$viewId'
      preLoaderRoute: typeof SpacesSpaceIdViewsViewIdRouteImport
      parentRoute: typeof SpacesSpaceIdViewsRoute
    }
    '/spaces/$spaceId/tasks/$taskId': {
      id: '/spaces/$spaceId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/spaces/$spaceId/tasks/$taskId'
      preLoaderRoute: typeof SpacesSpaceIdTasksTaskIdRouteImport
      parentRoute: typeof SpacesSpaceIdTasksRoute
    }
    '/spaces/$spaceId/projects/$projectId': {
      id: '/spaces/$spaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/spaces/$spaceId/projects/$projectId'
      preLoaderRoute: typeof SpacesSpaceIdProjectsProjectIdRouteImport
      parentRoute: typeof SpacesSpaceIdProjectsRoute
    }
  }
}

interface AllProjectsRouteChildren {
  AllProjectsProjectIdRoute: typeof AllProjectsProjectIdRoute
}

const AllProjectsRouteChildren: AllProjectsRouteChildren = {
  AllProjectsProjectIdRoute: AllProjectsProjectIdRoute,
}

const AllProjectsRouteWithChildren = AllProjectsRoute._addFileChildren(
  AllProjectsRouteChildren,
)

interface AllViewsRouteChildren {
  AllViewsViewIdRoute: typeof AllViewsViewIdRoute
}

const AllViewsRouteChildren: AllViewsRouteChildren = {
  AllViewsViewIdRoute: AllViewsViewIdRoute,
}

const AllViewsRouteWithChildren = AllViewsRoute._addFileChildren(
  AllViewsRouteChildren,
)

interface AllRouteChildren {
  AllArchiveRoute: typeof AllArchiveRoute
  AllInboxRoute: typeof AllInboxRoute
  AllNoProjectRoute: typeof AllNoProjectRoute
  AllProjectsRoute: typeof AllProjectsRouteWithChildren
  AllSettingsRoute: typeof AllSettingsRoute
  AllTasksRoute: typeof AllTasksRoute
  AllTrashRoute: typeof AllTrashRoute
  AllViewsRoute: typeof AllViewsRouteWithChildren
  AllIndexRoute: typeof AllIndexRoute
}

const AllRouteChildren: AllRouteChildren = {
  AllArchiveRoute: AllArchiveRoute,
  AllInboxRoute: AllInboxRoute,
  AllNoProjectRoute: AllNoProjectRoute,
  AllProjectsRoute: AllProjectsRouteWithChildren,
  AllSettingsRoute: AllSettingsRoute,
  AllTasksRoute: AllTasksRoute,
  AllTrashRoute: AllTrashRoute,
  AllViewsRoute: AllViewsRouteWithChildren,
  AllIndexRoute: AllIndexRoute,
}

const AllRouteWithChildren = AllRoute._addFileChildren(AllRouteChildren)

interface SpacesSpaceIdProjectsRouteChildren {
  SpacesSpaceIdProjectsProjectIdRoute: typeof SpacesSpaceIdProjectsProjectIdRoute
}

const SpacesSpaceIdProjectsRouteChildren: SpacesSpaceIdProjectsRouteChildren = {
  SpacesSpaceIdProjectsProjectIdRoute: SpacesSpaceIdProjectsProjectIdRoute,
}

const SpacesSpaceIdProjectsRouteWithChildren =
  SpacesSpaceIdProjectsRoute._addFileChildren(
    SpacesSpaceIdProjectsRouteChildren,
  )

interface SpacesSpaceIdTasksRouteChildren {
  SpacesSpaceIdTasksTaskIdRoute: typeof SpacesSpaceIdTasksTaskIdRoute
}

const SpacesSpaceIdTasksRouteChildren: SpacesSpaceIdTasksRouteChildren = {
  SpacesSpaceIdTasksTaskIdRoute: SpacesSpaceIdTasksTaskIdRoute,
}

const SpacesSpaceIdTasksRouteWithChildren =
  SpacesSpaceIdTasksRoute._addFileChildren(SpacesSpaceIdTasksRouteChildren)

interface SpacesSpaceIdViewsRouteChildren {
  SpacesSpaceIdViewsViewIdRoute: typeof SpacesSpaceIdViewsViewIdRoute
}

const SpacesSpaceIdViewsRouteChildren: SpacesSpaceIdViewsRouteChildren = {
  SpacesSpaceIdViewsViewIdRoute: SpacesSpaceIdViewsViewIdRoute,
}

const SpacesSpaceIdViewsRouteWithChildren =
  SpacesSpaceIdViewsRoute._addFileChildren(SpacesSpaceIdViewsRouteChildren)

interface SpacesSpaceIdRouteChildren {
  SpacesSpaceIdArchiveRoute: typeof SpacesSpaceIdArchiveRoute
  SpacesSpaceIdInboxRoute: typeof SpacesSpaceIdInboxRoute
  SpacesSpaceIdNoProjectRoute: typeof SpacesSpaceIdNoProjectRoute
  SpacesSpaceIdProjectsRoute: typeof SpacesSpaceIdProjectsRouteWithChildren
  SpacesSpaceIdSettingsRoute: typeof SpacesSpaceIdSettingsRoute
  SpacesSpaceIdTasksRoute: typeof SpacesSpaceIdTasksRouteWithChildren
  SpacesSpaceIdTrashRoute: typeof SpacesSpaceIdTrashRoute
  SpacesSpaceIdViewsRoute: typeof SpacesSpaceIdViewsRouteWithChildren
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
}

const SpacesSpaceIdRouteChildren: SpacesSpaceIdRouteChildren = {
  SpacesSpaceIdArchiveRoute: SpacesSpaceIdArchiveRoute,
  SpacesSpaceIdInboxRoute: SpacesSpaceIdInboxRoute,
  SpacesSpaceIdNoProjectRoute: SpacesSpaceIdNoProjectRoute,
  SpacesSpaceIdProjectsRoute: SpacesSpaceIdProjectsRouteWithChildren,
  SpacesSpaceIdSettingsRoute: SpacesSpaceIdSettingsRoute,
  SpacesSpaceIdTasksRoute: SpacesSpaceIdTasksRouteWithChildren,
  SpacesSpaceIdTrashRoute: SpacesSpaceIdTrashRoute,
  SpacesSpaceIdViewsRoute: SpacesSpaceIdViewsRouteWithChildren,
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
}

const SpacesSpaceIdRouteWithChildren = SpacesSpaceIdRoute._addFileChildren(
  SpacesSpaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRouteWithChildren,
  QuickCreateRoute: QuickCreateRoute,
  SettingsRoute: SettingsRoute,
  DebugActivityRoute: DebugActivityRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
