/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as ShellScopeKeyRouteRouteImport } from './routes/_shell/$scopeKey/route'
import { Route as DebugActivityRouteImport } from './routes/debug.activity'
import { Route as ShellScopeKeyIndexRouteImport } from './routes/_shell/$scopeKey/index'
import { Route as ShellScopeKeyArchiveRouteImport } from './routes/_shell/$scopeKey/archive'
import { Route as ShellScopeKeyProjectsRouteRouteImport } from './routes/_shell/$scopeKey/projects/route'
import { Route as ShellScopeKeySettingsRouteRouteImport } from './routes/_shell/$scopeKey/settings/route'
import { Route as ShellScopeKeyStandaloneRouteImport } from './routes/_shell/$scopeKey/standalone'
import { Route as ShellScopeKeyTasksRouteRouteImport } from './routes/_shell/$scopeKey/tasks/route'
import { Route as ShellScopeKeyTrashRouteImport } from './routes/_shell/$scopeKey/trash'
import { Route as ShellScopeKeyViewsRouteRouteImport } from './routes/_shell/$scopeKey/views/route'
import { Route as ShellScopeKeyProjectsIndexRouteImport } from './routes/_shell/$scopeKey/projects/index'
import { Route as ShellScopeKeyProjectsProjectIdRouteImport } from './routes/_shell/$scopeKey/projects/$projectId'
import { Route as ShellScopeKeySettingsIndexRouteImport } from './routes/_shell/$scopeKey/settings/index'
import { Route as ShellScopeKeySettingsSectionRouteImport } from './routes/_shell/$scopeKey/settings/$section'
import { Route as ShellScopeKeyTasksIndexRouteImport } from './routes/_shell/$scopeKey/tasks/index'
import { Route as ShellScopeKeyTasksTaskIdRouteImport } from './routes/_shell/$scopeKey/tasks/$taskId'
import { Route as ShellScopeKeyViewsIndexRouteImport } from './routes/_shell/$scopeKey/views/index'
import { Route as ShellScopeKeyViewsViewIdRouteImport } from './routes/_shell/$scopeKey/views/$viewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellScopeKeyRouteRoute = ShellScopeKeyRouteRouteImport.update({
  id: '/$scopeKey',
  path: '/$scopeKey',
  getParentRoute: () => ShellRouteRoute,
} as any)
const DebugActivityRoute = DebugActivityRouteImport.update({
  id: '/debug/activity',
  path: '/debug/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellScopeKeyIndexRoute = ShellScopeKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyArchiveRoute = ShellScopeKeyArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyProjectsRouteRoute =
  ShellScopeKeyProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ShellScopeKeyRouteRoute,
  } as any)
const ShellScopeKeySettingsRouteRoute =
  ShellScopeKeySettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ShellScopeKeyRouteRoute,
  } as any)
const ShellScopeKeyStandaloneRoute = ShellScopeKeyStandaloneRouteImport.update({
  id: '/standalone',
  path: '/standalone',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyTasksRouteRoute = ShellScopeKeyTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyTrashRoute = ShellScopeKeyTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyViewsRouteRoute = ShellScopeKeyViewsRouteRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => ShellScopeKeyRouteRoute,
} as any)
const ShellScopeKeyProjectsIndexRoute =
  ShellScopeKeyProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellScopeKeyProjectsRouteRoute,
  } as any)
const ShellScopeKeyProjectsProjectIdRoute =
  ShellScopeKeyProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ShellScopeKeyProjectsRouteRoute,
  } as any)
const ShellScopeKeySettingsIndexRoute =
  ShellScopeKeySettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellScopeKeySettingsRouteRoute,
  } as any)
const ShellScopeKeySettingsSectionRoute =
  ShellScopeKeySettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => ShellScopeKeySettingsRouteRoute,
  } as any)
const ShellScopeKeyTasksIndexRoute = ShellScopeKeyTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellScopeKeyTasksRouteRoute,
} as any)
const ShellScopeKeyTasksTaskIdRoute =
  ShellScopeKeyTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ShellScopeKeyTasksRouteRoute,
  } as any)
const ShellScopeKeyViewsIndexRoute = ShellScopeKeyViewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellScopeKeyViewsRouteRoute,
} as any)
const ShellScopeKeyViewsViewIdRoute =
  ShellScopeKeyViewsViewIdRouteImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => ShellScopeKeyViewsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/$scopeKey': typeof ShellScopeKeyRouteRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/$scopeKey/projects': typeof ShellScopeKeyProjectsRouteRouteWithChildren
  '/$scopeKey/settings': typeof ShellScopeKeySettingsRouteRouteWithChildren
  '/$scopeKey/tasks': typeof ShellScopeKeyTasksRouteRouteWithChildren
  '/$scopeKey/views': typeof ShellScopeKeyViewsRouteRouteWithChildren
  '/$scopeKey/archive': typeof ShellScopeKeyArchiveRoute
  '/$scopeKey/standalone': typeof ShellScopeKeyStandaloneRoute
  '/$scopeKey/trash': typeof ShellScopeKeyTrashRoute
  '/$scopeKey/': typeof ShellScopeKeyIndexRoute
  '/$scopeKey/projects/$projectId': typeof ShellScopeKeyProjectsProjectIdRoute
  '/$scopeKey/settings/$section': typeof ShellScopeKeySettingsSectionRoute
  '/$scopeKey/tasks/$taskId': typeof ShellScopeKeyTasksTaskIdRoute
  '/$scopeKey/views/$viewId': typeof ShellScopeKeyViewsViewIdRoute
  '/$scopeKey/projects/': typeof ShellScopeKeyProjectsIndexRoute
  '/$scopeKey/settings/': typeof ShellScopeKeySettingsIndexRoute
  '/$scopeKey/tasks/': typeof ShellScopeKeyTasksIndexRoute
  '/$scopeKey/views/': typeof ShellScopeKeyViewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/debug/activity': typeof DebugActivityRoute
  '/$scopeKey/archive': typeof ShellScopeKeyArchiveRoute
  '/$scopeKey/standalone': typeof ShellScopeKeyStandaloneRoute
  '/$scopeKey/trash': typeof ShellScopeKeyTrashRoute
  '/$scopeKey': typeof ShellScopeKeyIndexRoute
  '/$scopeKey/projects/$projectId': typeof ShellScopeKeyProjectsProjectIdRoute
  '/$scopeKey/settings/$section': typeof ShellScopeKeySettingsSectionRoute
  '/$scopeKey/tasks/$taskId': typeof ShellScopeKeyTasksTaskIdRoute
  '/$scopeKey/views/$viewId': typeof ShellScopeKeyViewsViewIdRoute
  '/$scopeKey/projects': typeof ShellScopeKeyProjectsIndexRoute
  '/$scopeKey/settings': typeof ShellScopeKeySettingsIndexRoute
  '/$scopeKey/tasks': typeof ShellScopeKeyTasksIndexRoute
  '/$scopeKey/views': typeof ShellScopeKeyViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteRouteWithChildren
  '/launcher': typeof LauncherRoute
  '/_shell/$scopeKey': typeof ShellScopeKeyRouteRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/_shell/$scopeKey/projects': typeof ShellScopeKeyProjectsRouteRouteWithChildren
  '/_shell/$scopeKey/settings': typeof ShellScopeKeySettingsRouteRouteWithChildren
  '/_shell/$scopeKey/tasks': typeof ShellScopeKeyTasksRouteRouteWithChildren
  '/_shell/$scopeKey/views': typeof ShellScopeKeyViewsRouteRouteWithChildren
  '/_shell/$scopeKey/archive': typeof ShellScopeKeyArchiveRoute
  '/_shell/$scopeKey/standalone': typeof ShellScopeKeyStandaloneRoute
  '/_shell/$scopeKey/trash': typeof ShellScopeKeyTrashRoute
  '/_shell/$scopeKey/': typeof ShellScopeKeyIndexRoute
  '/_shell/$scopeKey/projects/$projectId': typeof ShellScopeKeyProjectsProjectIdRoute
  '/_shell/$scopeKey/settings/$section': typeof ShellScopeKeySettingsSectionRoute
  '/_shell/$scopeKey/tasks/$taskId': typeof ShellScopeKeyTasksTaskIdRoute
  '/_shell/$scopeKey/views/$viewId': typeof ShellScopeKeyViewsViewIdRoute
  '/_shell/$scopeKey/projects/': typeof ShellScopeKeyProjectsIndexRoute
  '/_shell/$scopeKey/settings/': typeof ShellScopeKeySettingsIndexRoute
  '/_shell/$scopeKey/tasks/': typeof ShellScopeKeyTasksIndexRoute
  '/_shell/$scopeKey/views/': typeof ShellScopeKeyViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launcher'
    | '/$scopeKey'
    | '/debug/activity'
    | '/$scopeKey/projects'
    | '/$scopeKey/settings'
    | '/$scopeKey/tasks'
    | '/$scopeKey/views'
    | '/$scopeKey/archive'
    | '/$scopeKey/standalone'
    | '/$scopeKey/trash'
    | '/$scopeKey/'
    | '/$scopeKey/projects/$projectId'
    | '/$scopeKey/settings/$section'
    | '/$scopeKey/tasks/$taskId'
    | '/$scopeKey/views/$viewId'
    | '/$scopeKey/projects/'
    | '/$scopeKey/settings/'
    | '/$scopeKey/tasks/'
    | '/$scopeKey/views/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launcher'
    | '/debug/activity'
    | '/$scopeKey/archive'
    | '/$scopeKey/standalone'
    | '/$scopeKey/trash'
    | '/$scopeKey'
    | '/$scopeKey/projects/$projectId'
    | '/$scopeKey/settings/$section'
    | '/$scopeKey/tasks/$taskId'
    | '/$scopeKey/views/$viewId'
    | '/$scopeKey/projects'
    | '/$scopeKey/settings'
    | '/$scopeKey/tasks'
    | '/$scopeKey/views'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/launcher'
    | '/_shell/$scopeKey'
    | '/debug/activity'
    | '/_shell/$scopeKey/projects'
    | '/_shell/$scopeKey/settings'
    | '/_shell/$scopeKey/tasks'
    | '/_shell/$scopeKey/views'
    | '/_shell/$scopeKey/archive'
    | '/_shell/$scopeKey/standalone'
    | '/_shell/$scopeKey/trash'
    | '/_shell/$scopeKey/'
    | '/_shell/$scopeKey/projects/$projectId'
    | '/_shell/$scopeKey/settings/$section'
    | '/_shell/$scopeKey/tasks/$taskId'
    | '/_shell/$scopeKey/views/$viewId'
    | '/_shell/$scopeKey/projects/'
    | '/_shell/$scopeKey/settings/'
    | '/_shell/$scopeKey/tasks/'
    | '/_shell/$scopeKey/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
  LauncherRoute: typeof LauncherRoute
  DebugActivityRoute: typeof DebugActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/$scopeKey': {
      id: '/_shell/$scopeKey'
      path: '/$scopeKey'
      fullPath: '/$scopeKey'
      preLoaderRoute: typeof ShellScopeKeyRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/debug/activity': {
      id: '/debug/activity'
      path: '/debug/activity'
      fullPath: '/debug/activity'
      preLoaderRoute: typeof DebugActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/$scopeKey/': {
      id: '/_shell/$scopeKey/'
      path: '/'
      fullPath: '/$scopeKey/'
      preLoaderRoute: typeof ShellScopeKeyIndexRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/archive': {
      id: '/_shell/$scopeKey/archive'
      path: '/archive'
      fullPath: '/$scopeKey/archive'
      preLoaderRoute: typeof ShellScopeKeyArchiveRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/projects': {
      id: '/_shell/$scopeKey/projects'
      path: '/projects'
      fullPath: '/$scopeKey/projects'
      preLoaderRoute: typeof ShellScopeKeyProjectsRouteRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/settings': {
      id: '/_shell/$scopeKey/settings'
      path: '/settings'
      fullPath: '/$scopeKey/settings'
      preLoaderRoute: typeof ShellScopeKeySettingsRouteRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/standalone': {
      id: '/_shell/$scopeKey/standalone'
      path: '/standalone'
      fullPath: '/$scopeKey/standalone'
      preLoaderRoute: typeof ShellScopeKeyStandaloneRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/tasks': {
      id: '/_shell/$scopeKey/tasks'
      path: '/tasks'
      fullPath: '/$scopeKey/tasks'
      preLoaderRoute: typeof ShellScopeKeyTasksRouteRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/trash': {
      id: '/_shell/$scopeKey/trash'
      path: '/trash'
      fullPath: '/$scopeKey/trash'
      preLoaderRoute: typeof ShellScopeKeyTrashRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/views': {
      id: '/_shell/$scopeKey/views'
      path: '/views'
      fullPath: '/$scopeKey/views'
      preLoaderRoute: typeof ShellScopeKeyViewsRouteRouteImport
      parentRoute: typeof ShellScopeKeyRouteRoute
    }
    '/_shell/$scopeKey/projects/': {
      id: '/_shell/$scopeKey/projects/'
      path: '/'
      fullPath: '/$scopeKey/projects/'
      preLoaderRoute: typeof ShellScopeKeyProjectsIndexRouteImport
      parentRoute: typeof ShellScopeKeyProjectsRouteRoute
    }
    '/_shell/$scopeKey/projects/$projectId': {
      id: '/_shell/$scopeKey/projects/$projectId'
      path: '/$projectId'
      fullPath: '/$scopeKey/projects/$projectId'
      preLoaderRoute: typeof ShellScopeKeyProjectsProjectIdRouteImport
      parentRoute: typeof ShellScopeKeyProjectsRouteRoute
    }
    '/_shell/$scopeKey/settings/': {
      id: '/_shell/$scopeKey/settings/'
      path: '/'
      fullPath: '/$scopeKey/settings/'
      preLoaderRoute: typeof ShellScopeKeySettingsIndexRouteImport
      parentRoute: typeof ShellScopeKeySettingsRouteRoute
    }
    '/_shell/$scopeKey/settings/$section': {
      id: '/_shell/$scopeKey/settings/$section'
      path: '/$section'
      fullPath: '/$scopeKey/settings/$section'
      preLoaderRoute: typeof ShellScopeKeySettingsSectionRouteImport
      parentRoute: typeof ShellScopeKeySettingsRouteRoute
    }
    '/_shell/$scopeKey/tasks/': {
      id: '/_shell/$scopeKey/tasks/'
      path: '/'
      fullPath: '/$scopeKey/tasks/'
      preLoaderRoute: typeof ShellScopeKeyTasksIndexRouteImport
      parentRoute: typeof ShellScopeKeyTasksRouteRoute
    }
    '/_shell/$scopeKey/tasks/$taskId': {
      id: '/_shell/$scopeKey/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/$scopeKey/tasks/$taskId'
      preLoaderRoute: typeof ShellScopeKeyTasksTaskIdRouteImport
      parentRoute: typeof ShellScopeKeyTasksRouteRoute
    }
    '/_shell/$scopeKey/views/': {
      id: '/_shell/$scopeKey/views/'
      path: '/'
      fullPath: '/$scopeKey/views/'
      preLoaderRoute: typeof ShellScopeKeyViewsIndexRouteImport
      parentRoute: typeof ShellScopeKeyViewsRouteRoute
    }
    '/_shell/$scopeKey/views/$viewId': {
      id: '/_shell/$scopeKey/views/$viewId'
      path: '/$viewId'
      fullPath: '/$scopeKey/views/$viewId'
      preLoaderRoute: typeof ShellScopeKeyViewsViewIdRouteImport
      parentRoute: typeof ShellScopeKeyViewsRouteRoute
    }
  }
}

interface ShellScopeKeyProjectsRouteRouteChildren {
  ShellScopeKeyProjectsProjectIdRoute: typeof ShellScopeKeyProjectsProjectIdRoute
  ShellScopeKeyProjectsIndexRoute: typeof ShellScopeKeyProjectsIndexRoute
}

const ShellScopeKeyProjectsRouteRouteChildren: ShellScopeKeyProjectsRouteRouteChildren =
  {
    ShellScopeKeyProjectsProjectIdRoute: ShellScopeKeyProjectsProjectIdRoute,
    ShellScopeKeyProjectsIndexRoute: ShellScopeKeyProjectsIndexRoute,
  }

const ShellScopeKeyProjectsRouteRouteWithChildren =
  ShellScopeKeyProjectsRouteRoute._addFileChildren(
    ShellScopeKeyProjectsRouteRouteChildren,
  )

interface ShellScopeKeySettingsRouteRouteChildren {
  ShellScopeKeySettingsSectionRoute: typeof ShellScopeKeySettingsSectionRoute
  ShellScopeKeySettingsIndexRoute: typeof ShellScopeKeySettingsIndexRoute
}

const ShellScopeKeySettingsRouteRouteChildren: ShellScopeKeySettingsRouteRouteChildren =
  {
    ShellScopeKeySettingsSectionRoute: ShellScopeKeySettingsSectionRoute,
    ShellScopeKeySettingsIndexRoute: ShellScopeKeySettingsIndexRoute,
  }

const ShellScopeKeySettingsRouteRouteWithChildren =
  ShellScopeKeySettingsRouteRoute._addFileChildren(
    ShellScopeKeySettingsRouteRouteChildren,
  )

interface ShellScopeKeyTasksRouteRouteChildren {
  ShellScopeKeyTasksTaskIdRoute: typeof ShellScopeKeyTasksTaskIdRoute
  ShellScopeKeyTasksIndexRoute: typeof ShellScopeKeyTasksIndexRoute
}

const ShellScopeKeyTasksRouteRouteChildren: ShellScopeKeyTasksRouteRouteChildren =
  {
    ShellScopeKeyTasksTaskIdRoute: ShellScopeKeyTasksTaskIdRoute,
    ShellScopeKeyTasksIndexRoute: ShellScopeKeyTasksIndexRoute,
  }

const ShellScopeKeyTasksRouteRouteWithChildren =
  ShellScopeKeyTasksRouteRoute._addFileChildren(
    ShellScopeKeyTasksRouteRouteChildren,
  )

interface ShellScopeKeyViewsRouteRouteChildren {
  ShellScopeKeyViewsViewIdRoute: typeof ShellScopeKeyViewsViewIdRoute
  ShellScopeKeyViewsIndexRoute: typeof ShellScopeKeyViewsIndexRoute
}

const ShellScopeKeyViewsRouteRouteChildren: ShellScopeKeyViewsRouteRouteChildren =
  {
    ShellScopeKeyViewsViewIdRoute: ShellScopeKeyViewsViewIdRoute,
    ShellScopeKeyViewsIndexRoute: ShellScopeKeyViewsIndexRoute,
  }

const ShellScopeKeyViewsRouteRouteWithChildren =
  ShellScopeKeyViewsRouteRoute._addFileChildren(
    ShellScopeKeyViewsRouteRouteChildren,
  )

interface ShellScopeKeyRouteRouteChildren {
  ShellScopeKeyProjectsRouteRoute: typeof ShellScopeKeyProjectsRouteRouteWithChildren
  ShellScopeKeySettingsRouteRoute: typeof ShellScopeKeySettingsRouteRouteWithChildren
  ShellScopeKeyTasksRouteRoute: typeof ShellScopeKeyTasksRouteRouteWithChildren
  ShellScopeKeyViewsRouteRoute: typeof ShellScopeKeyViewsRouteRouteWithChildren
  ShellScopeKeyArchiveRoute: typeof ShellScopeKeyArchiveRoute
  ShellScopeKeyStandaloneRoute: typeof ShellScopeKeyStandaloneRoute
  ShellScopeKeyTrashRoute: typeof ShellScopeKeyTrashRoute
  ShellScopeKeyIndexRoute: typeof ShellScopeKeyIndexRoute
}

const ShellScopeKeyRouteRouteChildren: ShellScopeKeyRouteRouteChildren = {
  ShellScopeKeyProjectsRouteRoute: ShellScopeKeyProjectsRouteRouteWithChildren,
  ShellScopeKeySettingsRouteRoute: ShellScopeKeySettingsRouteRouteWithChildren,
  ShellScopeKeyTasksRouteRoute: ShellScopeKeyTasksRouteRouteWithChildren,
  ShellScopeKeyViewsRouteRoute: ShellScopeKeyViewsRouteRouteWithChildren,
  ShellScopeKeyArchiveRoute: ShellScopeKeyArchiveRoute,
  ShellScopeKeyStandaloneRoute: ShellScopeKeyStandaloneRoute,
  ShellScopeKeyTrashRoute: ShellScopeKeyTrashRoute,
  ShellScopeKeyIndexRoute: ShellScopeKeyIndexRoute,
}

const ShellScopeKeyRouteRouteWithChildren =
  ShellScopeKeyRouteRoute._addFileChildren(ShellScopeKeyRouteRouteChildren)

interface ShellRouteRouteChildren {
  ShellScopeKeyRouteRoute: typeof ShellScopeKeyRouteRouteWithChildren
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellScopeKeyRouteRoute: ShellScopeKeyRouteRouteWithChildren,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRouteRoute: ShellRouteRouteWithChildren,
  LauncherRoute: LauncherRoute,
  DebugActivityRoute: DebugActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
