/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuickCreateRouteImport } from './routes/quick-create'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugActivityRouteImport } from './routes/debug.activity'
import { Route as ShellAllRouteRouteImport } from './routes/_shell/all/route'
import { Route as ShellAllIndexRouteImport } from './routes/_shell/all/index'
import { Route as ShellAllTrashRouteImport } from './routes/_shell/all/trash'
import { Route as ShellAllSettingsRouteImport } from './routes/_shell/all/settings'
import { Route as ShellAllNoProjectRouteImport } from './routes/_shell/all/no-project'
import { Route as ShellAllInboxRouteImport } from './routes/_shell/all/inbox'
import { Route as ShellAllArchiveRouteImport } from './routes/_shell/all/archive'
import { Route as ShellSpacesSpaceIdRouteRouteImport } from './routes/_shell/spaces/$spaceId/route'
import { Route as ShellAllViewsRouteRouteImport } from './routes/_shell/all/views/route'
import { Route as ShellAllTasksRouteRouteImport } from './routes/_shell/all/tasks/route'
import { Route as ShellAllProjectsRouteRouteImport } from './routes/_shell/all/projects/route'
import { Route as ShellSpacesSpaceIdIndexRouteImport } from './routes/_shell/spaces/$spaceId/index'
import { Route as ShellAllViewsIndexRouteImport } from './routes/_shell/all/views/index'
import { Route as ShellAllTasksIndexRouteImport } from './routes/_shell/all/tasks/index'
import { Route as ShellAllProjectsIndexRouteImport } from './routes/_shell/all/projects/index'
import { Route as ShellSpacesSpaceIdTrashRouteImport } from './routes/_shell/spaces/$spaceId/trash'
import { Route as ShellSpacesSpaceIdSettingsRouteImport } from './routes/_shell/spaces/$spaceId/settings'
import { Route as ShellSpacesSpaceIdNoProjectRouteImport } from './routes/_shell/spaces/$spaceId/no-project'
import { Route as ShellSpacesSpaceIdInboxRouteImport } from './routes/_shell/spaces/$spaceId/inbox'
import { Route as ShellSpacesSpaceIdArchiveRouteImport } from './routes/_shell/spaces/$spaceId/archive'
import { Route as ShellAllViewsViewIdRouteImport } from './routes/_shell/all/views/$viewId'
import { Route as ShellAllProjectsProjectIdRouteImport } from './routes/_shell/all/projects/$projectId'
import { Route as ShellSpacesSpaceIdViewsRouteRouteImport } from './routes/_shell/spaces/$spaceId/views/route'
import { Route as ShellSpacesSpaceIdTasksRouteRouteImport } from './routes/_shell/spaces/$spaceId/tasks/route'
import { Route as ShellSpacesSpaceIdProjectsRouteRouteImport } from './routes/_shell/spaces/$spaceId/projects/route'
import { Route as ShellSpacesSpaceIdViewsIndexRouteImport } from './routes/_shell/spaces/$spaceId/views/index'
import { Route as ShellSpacesSpaceIdTasksIndexRouteImport } from './routes/_shell/spaces/$spaceId/tasks/index'
import { Route as ShellSpacesSpaceIdProjectsIndexRouteImport } from './routes/_shell/spaces/$spaceId/projects/index'
import { Route as ShellSpacesSpaceIdViewsViewIdRouteImport } from './routes/_shell/spaces/$spaceId/views/$viewId'
import { Route as ShellSpacesSpaceIdTasksTaskIdRouteImport } from './routes/_shell/spaces/$spaceId/tasks/$taskId'
import { Route as ShellSpacesSpaceIdProjectsProjectIdRouteImport } from './routes/_shell/spaces/$spaceId/projects/$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickCreateRoute = QuickCreateRouteImport.update({
  id: '/quick-create',
  path: '/quick-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugActivityRoute = DebugActivityRouteImport.update({
  id: '/debug/activity',
  path: '/debug/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAllRouteRoute = ShellAllRouteRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAllIndexRoute = ShellAllIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllTrashRoute = ShellAllTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllSettingsRoute = ShellAllSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllNoProjectRoute = ShellAllNoProjectRouteImport.update({
  id: '/no-project',
  path: '/no-project',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllInboxRoute = ShellAllInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllArchiveRoute = ShellAllArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellSpacesSpaceIdRouteRoute = ShellSpacesSpaceIdRouteRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAllViewsRouteRoute = ShellAllViewsRouteRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllTasksRouteRoute = ShellAllTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellAllProjectsRouteRoute = ShellAllProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellAllRouteRoute,
} as any)
const ShellSpacesSpaceIdIndexRoute = ShellSpacesSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
} as any)
const ShellAllViewsIndexRoute = ShellAllViewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAllViewsRouteRoute,
} as any)
const ShellAllTasksIndexRoute = ShellAllTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAllTasksRouteRoute,
} as any)
const ShellAllProjectsIndexRoute = ShellAllProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAllProjectsRouteRoute,
} as any)
const ShellSpacesSpaceIdTrashRoute = ShellSpacesSpaceIdTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
} as any)
const ShellSpacesSpaceIdSettingsRoute =
  ShellSpacesSpaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellSpacesSpaceIdNoProjectRoute =
  ShellSpacesSpaceIdNoProjectRouteImport.update({
    id: '/no-project',
    path: '/no-project',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellSpacesSpaceIdInboxRoute = ShellSpacesSpaceIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
} as any)
const ShellSpacesSpaceIdArchiveRoute =
  ShellSpacesSpaceIdArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellAllViewsViewIdRoute = ShellAllViewsViewIdRouteImport.update({
  id: '/$viewId',
  path: '/$viewId',
  getParentRoute: () => ShellAllViewsRouteRoute,
} as any)
const ShellAllProjectsProjectIdRoute =
  ShellAllProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ShellAllProjectsRouteRoute,
  } as any)
const ShellSpacesSpaceIdViewsRouteRoute =
  ShellSpacesSpaceIdViewsRouteRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellSpacesSpaceIdTasksRouteRoute =
  ShellSpacesSpaceIdTasksRouteRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellSpacesSpaceIdProjectsRouteRoute =
  ShellSpacesSpaceIdProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ShellSpacesSpaceIdRouteRoute,
  } as any)
const ShellSpacesSpaceIdViewsIndexRoute =
  ShellSpacesSpaceIdViewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellSpacesSpaceIdViewsRouteRoute,
  } as any)
const ShellSpacesSpaceIdTasksIndexRoute =
  ShellSpacesSpaceIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellSpacesSpaceIdTasksRouteRoute,
  } as any)
const ShellSpacesSpaceIdProjectsIndexRoute =
  ShellSpacesSpaceIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellSpacesSpaceIdProjectsRouteRoute,
  } as any)
const ShellSpacesSpaceIdViewsViewIdRoute =
  ShellSpacesSpaceIdViewsViewIdRouteImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => ShellSpacesSpaceIdViewsRouteRoute,
  } as any)
const ShellSpacesSpaceIdTasksTaskIdRoute =
  ShellSpacesSpaceIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ShellSpacesSpaceIdTasksRouteRoute,
  } as any)
const ShellSpacesSpaceIdProjectsProjectIdRoute =
  ShellSpacesSpaceIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ShellSpacesSpaceIdProjectsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/all': typeof ShellAllRouteRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/all/projects': typeof ShellAllProjectsRouteRouteWithChildren
  '/all/tasks': typeof ShellAllTasksRouteRouteWithChildren
  '/all/views': typeof ShellAllViewsRouteRouteWithChildren
  '/spaces/$spaceId': typeof ShellSpacesSpaceIdRouteRouteWithChildren
  '/all/archive': typeof ShellAllArchiveRoute
  '/all/inbox': typeof ShellAllInboxRoute
  '/all/no-project': typeof ShellAllNoProjectRoute
  '/all/settings': typeof ShellAllSettingsRoute
  '/all/trash': typeof ShellAllTrashRoute
  '/all/': typeof ShellAllIndexRoute
  '/spaces/$spaceId/projects': typeof ShellSpacesSpaceIdProjectsRouteRouteWithChildren
  '/spaces/$spaceId/tasks': typeof ShellSpacesSpaceIdTasksRouteRouteWithChildren
  '/spaces/$spaceId/views': typeof ShellSpacesSpaceIdViewsRouteRouteWithChildren
  '/all/projects/$projectId': typeof ShellAllProjectsProjectIdRoute
  '/all/views/$viewId': typeof ShellAllViewsViewIdRoute
  '/spaces/$spaceId/archive': typeof ShellSpacesSpaceIdArchiveRoute
  '/spaces/$spaceId/inbox': typeof ShellSpacesSpaceIdInboxRoute
  '/spaces/$spaceId/no-project': typeof ShellSpacesSpaceIdNoProjectRoute
  '/spaces/$spaceId/settings': typeof ShellSpacesSpaceIdSettingsRoute
  '/spaces/$spaceId/trash': typeof ShellSpacesSpaceIdTrashRoute
  '/all/projects/': typeof ShellAllProjectsIndexRoute
  '/all/tasks/': typeof ShellAllTasksIndexRoute
  '/all/views/': typeof ShellAllViewsIndexRoute
  '/spaces/$spaceId/': typeof ShellSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/projects/$projectId': typeof ShellSpacesSpaceIdProjectsProjectIdRoute
  '/spaces/$spaceId/tasks/$taskId': typeof ShellSpacesSpaceIdTasksTaskIdRoute
  '/spaces/$spaceId/views/$viewId': typeof ShellSpacesSpaceIdViewsViewIdRoute
  '/spaces/$spaceId/projects/': typeof ShellSpacesSpaceIdProjectsIndexRoute
  '/spaces/$spaceId/tasks/': typeof ShellSpacesSpaceIdTasksIndexRoute
  '/spaces/$spaceId/views/': typeof ShellSpacesSpaceIdViewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/debug/activity': typeof DebugActivityRoute
  '/all/archive': typeof ShellAllArchiveRoute
  '/all/inbox': typeof ShellAllInboxRoute
  '/all/no-project': typeof ShellAllNoProjectRoute
  '/all/settings': typeof ShellAllSettingsRoute
  '/all/trash': typeof ShellAllTrashRoute
  '/all': typeof ShellAllIndexRoute
  '/all/projects/$projectId': typeof ShellAllProjectsProjectIdRoute
  '/all/views/$viewId': typeof ShellAllViewsViewIdRoute
  '/spaces/$spaceId/archive': typeof ShellSpacesSpaceIdArchiveRoute
  '/spaces/$spaceId/inbox': typeof ShellSpacesSpaceIdInboxRoute
  '/spaces/$spaceId/no-project': typeof ShellSpacesSpaceIdNoProjectRoute
  '/spaces/$spaceId/settings': typeof ShellSpacesSpaceIdSettingsRoute
  '/spaces/$spaceId/trash': typeof ShellSpacesSpaceIdTrashRoute
  '/all/projects': typeof ShellAllProjectsIndexRoute
  '/all/tasks': typeof ShellAllTasksIndexRoute
  '/all/views': typeof ShellAllViewsIndexRoute
  '/spaces/$spaceId': typeof ShellSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/projects/$projectId': typeof ShellSpacesSpaceIdProjectsProjectIdRoute
  '/spaces/$spaceId/tasks/$taskId': typeof ShellSpacesSpaceIdTasksTaskIdRoute
  '/spaces/$spaceId/views/$viewId': typeof ShellSpacesSpaceIdViewsViewIdRoute
  '/spaces/$spaceId/projects': typeof ShellSpacesSpaceIdProjectsIndexRoute
  '/spaces/$spaceId/tasks': typeof ShellSpacesSpaceIdTasksIndexRoute
  '/spaces/$spaceId/views': typeof ShellSpacesSpaceIdViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteRouteWithChildren
  '/quick-create': typeof QuickCreateRoute
  '/settings': typeof SettingsRoute
  '/_shell/all': typeof ShellAllRouteRouteWithChildren
  '/debug/activity': typeof DebugActivityRoute
  '/_shell/all/projects': typeof ShellAllProjectsRouteRouteWithChildren
  '/_shell/all/tasks': typeof ShellAllTasksRouteRouteWithChildren
  '/_shell/all/views': typeof ShellAllViewsRouteRouteWithChildren
  '/_shell/spaces/$spaceId': typeof ShellSpacesSpaceIdRouteRouteWithChildren
  '/_shell/all/archive': typeof ShellAllArchiveRoute
  '/_shell/all/inbox': typeof ShellAllInboxRoute
  '/_shell/all/no-project': typeof ShellAllNoProjectRoute
  '/_shell/all/settings': typeof ShellAllSettingsRoute
  '/_shell/all/trash': typeof ShellAllTrashRoute
  '/_shell/all/': typeof ShellAllIndexRoute
  '/_shell/spaces/$spaceId/projects': typeof ShellSpacesSpaceIdProjectsRouteRouteWithChildren
  '/_shell/spaces/$spaceId/tasks': typeof ShellSpacesSpaceIdTasksRouteRouteWithChildren
  '/_shell/spaces/$spaceId/views': typeof ShellSpacesSpaceIdViewsRouteRouteWithChildren
  '/_shell/all/projects/$projectId': typeof ShellAllProjectsProjectIdRoute
  '/_shell/all/views/$viewId': typeof ShellAllViewsViewIdRoute
  '/_shell/spaces/$spaceId/archive': typeof ShellSpacesSpaceIdArchiveRoute
  '/_shell/spaces/$spaceId/inbox': typeof ShellSpacesSpaceIdInboxRoute
  '/_shell/spaces/$spaceId/no-project': typeof ShellSpacesSpaceIdNoProjectRoute
  '/_shell/spaces/$spaceId/settings': typeof ShellSpacesSpaceIdSettingsRoute
  '/_shell/spaces/$spaceId/trash': typeof ShellSpacesSpaceIdTrashRoute
  '/_shell/all/projects/': typeof ShellAllProjectsIndexRoute
  '/_shell/all/tasks/': typeof ShellAllTasksIndexRoute
  '/_shell/all/views/': typeof ShellAllViewsIndexRoute
  '/_shell/spaces/$spaceId/': typeof ShellSpacesSpaceIdIndexRoute
  '/_shell/spaces/$spaceId/projects/$projectId': typeof ShellSpacesSpaceIdProjectsProjectIdRoute
  '/_shell/spaces/$spaceId/tasks/$taskId': typeof ShellSpacesSpaceIdTasksTaskIdRoute
  '/_shell/spaces/$spaceId/views/$viewId': typeof ShellSpacesSpaceIdViewsViewIdRoute
  '/_shell/spaces/$spaceId/projects/': typeof ShellSpacesSpaceIdProjectsIndexRoute
  '/_shell/spaces/$spaceId/tasks/': typeof ShellSpacesSpaceIdTasksIndexRoute
  '/_shell/spaces/$spaceId/views/': typeof ShellSpacesSpaceIdViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quick-create'
    | '/settings'
    | '/all'
    | '/debug/activity'
    | '/all/projects'
    | '/all/tasks'
    | '/all/views'
    | '/spaces/$spaceId'
    | '/all/archive'
    | '/all/inbox'
    | '/all/no-project'
    | '/all/settings'
    | '/all/trash'
    | '/all/'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/tasks'
    | '/spaces/$spaceId/views'
    | '/all/projects/$projectId'
    | '/all/views/$viewId'
    | '/spaces/$spaceId/archive'
    | '/spaces/$spaceId/inbox'
    | '/spaces/$spaceId/no-project'
    | '/spaces/$spaceId/settings'
    | '/spaces/$spaceId/trash'
    | '/all/projects/'
    | '/all/tasks/'
    | '/all/views/'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/projects/$projectId'
    | '/spaces/$spaceId/tasks/$taskId'
    | '/spaces/$spaceId/views/$viewId'
    | '/spaces/$spaceId/projects/'
    | '/spaces/$spaceId/tasks/'
    | '/spaces/$spaceId/views/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quick-create'
    | '/settings'
    | '/debug/activity'
    | '/all/archive'
    | '/all/inbox'
    | '/all/no-project'
    | '/all/settings'
    | '/all/trash'
    | '/all'
    | '/all/projects/$projectId'
    | '/all/views/$viewId'
    | '/spaces/$spaceId/archive'
    | '/spaces/$spaceId/inbox'
    | '/spaces/$spaceId/no-project'
    | '/spaces/$spaceId/settings'
    | '/spaces/$spaceId/trash'
    | '/all/projects'
    | '/all/tasks'
    | '/all/views'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/projects/$projectId'
    | '/spaces/$spaceId/tasks/$taskId'
    | '/spaces/$spaceId/views/$viewId'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/tasks'
    | '/spaces/$spaceId/views'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/quick-create'
    | '/settings'
    | '/_shell/all'
    | '/debug/activity'
    | '/_shell/all/projects'
    | '/_shell/all/tasks'
    | '/_shell/all/views'
    | '/_shell/spaces/$spaceId'
    | '/_shell/all/archive'
    | '/_shell/all/inbox'
    | '/_shell/all/no-project'
    | '/_shell/all/settings'
    | '/_shell/all/trash'
    | '/_shell/all/'
    | '/_shell/spaces/$spaceId/projects'
    | '/_shell/spaces/$spaceId/tasks'
    | '/_shell/spaces/$spaceId/views'
    | '/_shell/all/projects/$projectId'
    | '/_shell/all/views/$viewId'
    | '/_shell/spaces/$spaceId/archive'
    | '/_shell/spaces/$spaceId/inbox'
    | '/_shell/spaces/$spaceId/no-project'
    | '/_shell/spaces/$spaceId/settings'
    | '/_shell/spaces/$spaceId/trash'
    | '/_shell/all/projects/'
    | '/_shell/all/tasks/'
    | '/_shell/all/views/'
    | '/_shell/spaces/$spaceId/'
    | '/_shell/spaces/$spaceId/projects/$projectId'
    | '/_shell/spaces/$spaceId/tasks/$taskId'
    | '/_shell/spaces/$spaceId/views/$viewId'
    | '/_shell/spaces/$spaceId/projects/'
    | '/_shell/spaces/$spaceId/tasks/'
    | '/_shell/spaces/$spaceId/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
  QuickCreateRoute: typeof QuickCreateRoute
  SettingsRoute: typeof SettingsRoute
  DebugActivityRoute: typeof DebugActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-create': {
      id: '/quick-create'
      path: '/quick-create'
      fullPath: '/quick-create'
      preLoaderRoute: typeof QuickCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/activity': {
      id: '/debug/activity'
      path: '/debug/activity'
      fullPath: '/debug/activity'
      preLoaderRoute: typeof DebugActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/all': {
      id: '/_shell/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof ShellAllRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/all/': {
      id: '/_shell/all/'
      path: '/'
      fullPath: '/all/'
      preLoaderRoute: typeof ShellAllIndexRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/trash': {
      id: '/_shell/all/trash'
      path: '/trash'
      fullPath: '/all/trash'
      preLoaderRoute: typeof ShellAllTrashRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/settings': {
      id: '/_shell/all/settings'
      path: '/settings'
      fullPath: '/all/settings'
      preLoaderRoute: typeof ShellAllSettingsRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/no-project': {
      id: '/_shell/all/no-project'
      path: '/no-project'
      fullPath: '/all/no-project'
      preLoaderRoute: typeof ShellAllNoProjectRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/inbox': {
      id: '/_shell/all/inbox'
      path: '/inbox'
      fullPath: '/all/inbox'
      preLoaderRoute: typeof ShellAllInboxRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/archive': {
      id: '/_shell/all/archive'
      path: '/archive'
      fullPath: '/all/archive'
      preLoaderRoute: typeof ShellAllArchiveRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/spaces/$spaceId': {
      id: '/_shell/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof ShellSpacesSpaceIdRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/all/views': {
      id: '/_shell/all/views'
      path: '/views'
      fullPath: '/all/views'
      preLoaderRoute: typeof ShellAllViewsRouteRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/tasks': {
      id: '/_shell/all/tasks'
      path: '/tasks'
      fullPath: '/all/tasks'
      preLoaderRoute: typeof ShellAllTasksRouteRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/all/projects': {
      id: '/_shell/all/projects'
      path: '/projects'
      fullPath: '/all/projects'
      preLoaderRoute: typeof ShellAllProjectsRouteRouteImport
      parentRoute: typeof ShellAllRouteRoute
    }
    '/_shell/spaces/$spaceId/': {
      id: '/_shell/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof ShellSpacesSpaceIdIndexRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/all/views/': {
      id: '/_shell/all/views/'
      path: '/'
      fullPath: '/all/views/'
      preLoaderRoute: typeof ShellAllViewsIndexRouteImport
      parentRoute: typeof ShellAllViewsRouteRoute
    }
    '/_shell/all/tasks/': {
      id: '/_shell/all/tasks/'
      path: '/'
      fullPath: '/all/tasks/'
      preLoaderRoute: typeof ShellAllTasksIndexRouteImport
      parentRoute: typeof ShellAllTasksRouteRoute
    }
    '/_shell/all/projects/': {
      id: '/_shell/all/projects/'
      path: '/'
      fullPath: '/all/projects/'
      preLoaderRoute: typeof ShellAllProjectsIndexRouteImport
      parentRoute: typeof ShellAllProjectsRouteRoute
    }
    '/_shell/spaces/$spaceId/trash': {
      id: '/_shell/spaces/$spaceId/trash'
      path: '/trash'
      fullPath: '/spaces/$spaceId/trash'
      preLoaderRoute: typeof ShellSpacesSpaceIdTrashRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/settings': {
      id: '/_shell/spaces/$spaceId/settings'
      path: '/settings'
      fullPath: '/spaces/$spaceId/settings'
      preLoaderRoute: typeof ShellSpacesSpaceIdSettingsRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/no-project': {
      id: '/_shell/spaces/$spaceId/no-project'
      path: '/no-project'
      fullPath: '/spaces/$spaceId/no-project'
      preLoaderRoute: typeof ShellSpacesSpaceIdNoProjectRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/inbox': {
      id: '/_shell/spaces/$spaceId/inbox'
      path: '/inbox'
      fullPath: '/spaces/$spaceId/inbox'
      preLoaderRoute: typeof ShellSpacesSpaceIdInboxRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/archive': {
      id: '/_shell/spaces/$spaceId/archive'
      path: '/archive'
      fullPath: '/spaces/$spaceId/archive'
      preLoaderRoute: typeof ShellSpacesSpaceIdArchiveRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/all/views/$viewId': {
      id: '/_shell/all/views/$viewId'
      path: '/$viewId'
      fullPath: '/all/views/$viewId'
      preLoaderRoute: typeof ShellAllViewsViewIdRouteImport
      parentRoute: typeof ShellAllViewsRouteRoute
    }
    '/_shell/all/projects/$projectId': {
      id: '/_shell/all/projects/$projectId'
      path: '/$projectId'
      fullPath: '/all/projects/$projectId'
      preLoaderRoute: typeof ShellAllProjectsProjectIdRouteImport
      parentRoute: typeof ShellAllProjectsRouteRoute
    }
    '/_shell/spaces/$spaceId/views': {
      id: '/_shell/spaces/$spaceId/views'
      path: '/views'
      fullPath: '/spaces/$spaceId/views'
      preLoaderRoute: typeof ShellSpacesSpaceIdViewsRouteRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/tasks': {
      id: '/_shell/spaces/$spaceId/tasks'
      path: '/tasks'
      fullPath: '/spaces/$spaceId/tasks'
      preLoaderRoute: typeof ShellSpacesSpaceIdTasksRouteRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/projects': {
      id: '/_shell/spaces/$spaceId/projects'
      path: '/projects'
      fullPath: '/spaces/$spaceId/projects'
      preLoaderRoute: typeof ShellSpacesSpaceIdProjectsRouteRouteImport
      parentRoute: typeof ShellSpacesSpaceIdRouteRoute
    }
    '/_shell/spaces/$spaceId/views/': {
      id: '/_shell/spaces/$spaceId/views/'
      path: '/'
      fullPath: '/spaces/$spaceId/views/'
      preLoaderRoute: typeof ShellSpacesSpaceIdViewsIndexRouteImport
      parentRoute: typeof ShellSpacesSpaceIdViewsRouteRoute
    }
    '/_shell/spaces/$spaceId/tasks/': {
      id: '/_shell/spaces/$spaceId/tasks/'
      path: '/'
      fullPath: '/spaces/$spaceId/tasks/'
      preLoaderRoute: typeof ShellSpacesSpaceIdTasksIndexRouteImport
      parentRoute: typeof ShellSpacesSpaceIdTasksRouteRoute
    }
    '/_shell/spaces/$spaceId/projects/': {
      id: '/_shell/spaces/$spaceId/projects/'
      path: '/'
      fullPath: '/spaces/$spaceId/projects/'
      preLoaderRoute: typeof ShellSpacesSpaceIdProjectsIndexRouteImport
      parentRoute: typeof ShellSpacesSpaceIdProjectsRouteRoute
    }
    '/_shell/spaces/$spaceId/views/$viewId': {
      id: '/_shell/spaces/$spaceId/views/$viewId'
      path: '/$viewId'
      fullPath: '/spaces/$spaceId/views/$viewId'
      preLoaderRoute: typeof ShellSpacesSpaceIdViewsViewIdRouteImport
      parentRoute: typeof ShellSpacesSpaceIdViewsRouteRoute
    }
    '/_shell/spaces/$spaceId/tasks/$taskId': {
      id: '/_shell/spaces/$spaceId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/spaces/$spaceId/tasks/$taskId'
      preLoaderRoute: typeof ShellSpacesSpaceIdTasksTaskIdRouteImport
      parentRoute: typeof ShellSpacesSpaceIdTasksRouteRoute
    }
    '/_shell/spaces/$spaceId/projects/$projectId': {
      id: '/_shell/spaces/$spaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/spaces/$spaceId/projects/$projectId'
      preLoaderRoute: typeof ShellSpacesSpaceIdProjectsProjectIdRouteImport
      parentRoute: typeof ShellSpacesSpaceIdProjectsRouteRoute
    }
  }
}

interface ShellAllProjectsRouteRouteChildren {
  ShellAllProjectsProjectIdRoute: typeof ShellAllProjectsProjectIdRoute
  ShellAllProjectsIndexRoute: typeof ShellAllProjectsIndexRoute
}

const ShellAllProjectsRouteRouteChildren: ShellAllProjectsRouteRouteChildren = {
  ShellAllProjectsProjectIdRoute: ShellAllProjectsProjectIdRoute,
  ShellAllProjectsIndexRoute: ShellAllProjectsIndexRoute,
}

const ShellAllProjectsRouteRouteWithChildren =
  ShellAllProjectsRouteRoute._addFileChildren(
    ShellAllProjectsRouteRouteChildren,
  )

interface ShellAllTasksRouteRouteChildren {
  ShellAllTasksIndexRoute: typeof ShellAllTasksIndexRoute
}

const ShellAllTasksRouteRouteChildren: ShellAllTasksRouteRouteChildren = {
  ShellAllTasksIndexRoute: ShellAllTasksIndexRoute,
}

const ShellAllTasksRouteRouteWithChildren =
  ShellAllTasksRouteRoute._addFileChildren(ShellAllTasksRouteRouteChildren)

interface ShellAllViewsRouteRouteChildren {
  ShellAllViewsViewIdRoute: typeof ShellAllViewsViewIdRoute
  ShellAllViewsIndexRoute: typeof ShellAllViewsIndexRoute
}

const ShellAllViewsRouteRouteChildren: ShellAllViewsRouteRouteChildren = {
  ShellAllViewsViewIdRoute: ShellAllViewsViewIdRoute,
  ShellAllViewsIndexRoute: ShellAllViewsIndexRoute,
}

const ShellAllViewsRouteRouteWithChildren =
  ShellAllViewsRouteRoute._addFileChildren(ShellAllViewsRouteRouteChildren)

interface ShellAllRouteRouteChildren {
  ShellAllProjectsRouteRoute: typeof ShellAllProjectsRouteRouteWithChildren
  ShellAllTasksRouteRoute: typeof ShellAllTasksRouteRouteWithChildren
  ShellAllViewsRouteRoute: typeof ShellAllViewsRouteRouteWithChildren
  ShellAllArchiveRoute: typeof ShellAllArchiveRoute
  ShellAllInboxRoute: typeof ShellAllInboxRoute
  ShellAllNoProjectRoute: typeof ShellAllNoProjectRoute
  ShellAllSettingsRoute: typeof ShellAllSettingsRoute
  ShellAllTrashRoute: typeof ShellAllTrashRoute
  ShellAllIndexRoute: typeof ShellAllIndexRoute
}

const ShellAllRouteRouteChildren: ShellAllRouteRouteChildren = {
  ShellAllProjectsRouteRoute: ShellAllProjectsRouteRouteWithChildren,
  ShellAllTasksRouteRoute: ShellAllTasksRouteRouteWithChildren,
  ShellAllViewsRouteRoute: ShellAllViewsRouteRouteWithChildren,
  ShellAllArchiveRoute: ShellAllArchiveRoute,
  ShellAllInboxRoute: ShellAllInboxRoute,
  ShellAllNoProjectRoute: ShellAllNoProjectRoute,
  ShellAllSettingsRoute: ShellAllSettingsRoute,
  ShellAllTrashRoute: ShellAllTrashRoute,
  ShellAllIndexRoute: ShellAllIndexRoute,
}

const ShellAllRouteRouteWithChildren = ShellAllRouteRoute._addFileChildren(
  ShellAllRouteRouteChildren,
)

interface ShellSpacesSpaceIdProjectsRouteRouteChildren {
  ShellSpacesSpaceIdProjectsProjectIdRoute: typeof ShellSpacesSpaceIdProjectsProjectIdRoute
  ShellSpacesSpaceIdProjectsIndexRoute: typeof ShellSpacesSpaceIdProjectsIndexRoute
}

const ShellSpacesSpaceIdProjectsRouteRouteChildren: ShellSpacesSpaceIdProjectsRouteRouteChildren =
  {
    ShellSpacesSpaceIdProjectsProjectIdRoute:
      ShellSpacesSpaceIdProjectsProjectIdRoute,
    ShellSpacesSpaceIdProjectsIndexRoute: ShellSpacesSpaceIdProjectsIndexRoute,
  }

const ShellSpacesSpaceIdProjectsRouteRouteWithChildren =
  ShellSpacesSpaceIdProjectsRouteRoute._addFileChildren(
    ShellSpacesSpaceIdProjectsRouteRouteChildren,
  )

interface ShellSpacesSpaceIdTasksRouteRouteChildren {
  ShellSpacesSpaceIdTasksTaskIdRoute: typeof ShellSpacesSpaceIdTasksTaskIdRoute
  ShellSpacesSpaceIdTasksIndexRoute: typeof ShellSpacesSpaceIdTasksIndexRoute
}

const ShellSpacesSpaceIdTasksRouteRouteChildren: ShellSpacesSpaceIdTasksRouteRouteChildren =
  {
    ShellSpacesSpaceIdTasksTaskIdRoute: ShellSpacesSpaceIdTasksTaskIdRoute,
    ShellSpacesSpaceIdTasksIndexRoute: ShellSpacesSpaceIdTasksIndexRoute,
  }

const ShellSpacesSpaceIdTasksRouteRouteWithChildren =
  ShellSpacesSpaceIdTasksRouteRoute._addFileChildren(
    ShellSpacesSpaceIdTasksRouteRouteChildren,
  )

interface ShellSpacesSpaceIdViewsRouteRouteChildren {
  ShellSpacesSpaceIdViewsViewIdRoute: typeof ShellSpacesSpaceIdViewsViewIdRoute
  ShellSpacesSpaceIdViewsIndexRoute: typeof ShellSpacesSpaceIdViewsIndexRoute
}

const ShellSpacesSpaceIdViewsRouteRouteChildren: ShellSpacesSpaceIdViewsRouteRouteChildren =
  {
    ShellSpacesSpaceIdViewsViewIdRoute: ShellSpacesSpaceIdViewsViewIdRoute,
    ShellSpacesSpaceIdViewsIndexRoute: ShellSpacesSpaceIdViewsIndexRoute,
  }

const ShellSpacesSpaceIdViewsRouteRouteWithChildren =
  ShellSpacesSpaceIdViewsRouteRoute._addFileChildren(
    ShellSpacesSpaceIdViewsRouteRouteChildren,
  )

interface ShellSpacesSpaceIdRouteRouteChildren {
  ShellSpacesSpaceIdProjectsRouteRoute: typeof ShellSpacesSpaceIdProjectsRouteRouteWithChildren
  ShellSpacesSpaceIdTasksRouteRoute: typeof ShellSpacesSpaceIdTasksRouteRouteWithChildren
  ShellSpacesSpaceIdViewsRouteRoute: typeof ShellSpacesSpaceIdViewsRouteRouteWithChildren
  ShellSpacesSpaceIdArchiveRoute: typeof ShellSpacesSpaceIdArchiveRoute
  ShellSpacesSpaceIdInboxRoute: typeof ShellSpacesSpaceIdInboxRoute
  ShellSpacesSpaceIdNoProjectRoute: typeof ShellSpacesSpaceIdNoProjectRoute
  ShellSpacesSpaceIdSettingsRoute: typeof ShellSpacesSpaceIdSettingsRoute
  ShellSpacesSpaceIdTrashRoute: typeof ShellSpacesSpaceIdTrashRoute
  ShellSpacesSpaceIdIndexRoute: typeof ShellSpacesSpaceIdIndexRoute
}

const ShellSpacesSpaceIdRouteRouteChildren: ShellSpacesSpaceIdRouteRouteChildren =
  {
    ShellSpacesSpaceIdProjectsRouteRoute:
      ShellSpacesSpaceIdProjectsRouteRouteWithChildren,
    ShellSpacesSpaceIdTasksRouteRoute:
      ShellSpacesSpaceIdTasksRouteRouteWithChildren,
    ShellSpacesSpaceIdViewsRouteRoute:
      ShellSpacesSpaceIdViewsRouteRouteWithChildren,
    ShellSpacesSpaceIdArchiveRoute: ShellSpacesSpaceIdArchiveRoute,
    ShellSpacesSpaceIdInboxRoute: ShellSpacesSpaceIdInboxRoute,
    ShellSpacesSpaceIdNoProjectRoute: ShellSpacesSpaceIdNoProjectRoute,
    ShellSpacesSpaceIdSettingsRoute: ShellSpacesSpaceIdSettingsRoute,
    ShellSpacesSpaceIdTrashRoute: ShellSpacesSpaceIdTrashRoute,
    ShellSpacesSpaceIdIndexRoute: ShellSpacesSpaceIdIndexRoute,
  }

const ShellSpacesSpaceIdRouteRouteWithChildren =
  ShellSpacesSpaceIdRouteRoute._addFileChildren(
    ShellSpacesSpaceIdRouteRouteChildren,
  )

interface ShellRouteRouteChildren {
  ShellAllRouteRoute: typeof ShellAllRouteRouteWithChildren
  ShellSpacesSpaceIdRouteRoute: typeof ShellSpacesSpaceIdRouteRouteWithChildren
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellAllRouteRoute: ShellAllRouteRouteWithChildren,
  ShellSpacesSpaceIdRouteRoute: ShellSpacesSpaceIdRouteRouteWithChildren,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRouteRoute: ShellRouteRouteWithChildren,
  QuickCreateRoute: QuickCreateRoute,
  SettingsRoute: SettingsRoute,
  DebugActivityRoute: DebugActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
