[package]
name = "stoneflow-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_test_support"
path = "src/lib.rs"

[dependencies]
stoneflow-domain = { path = "../domain" }
stoneflow-migration = { path = "../migration" }
stoneflow-storage = { path = "../storage", features = ["test-helpers"] }
stoneflow-usecase = { path = "../usecase" }
uuid.workspace = true
