[package]
name = "stoneflow-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "stoneflow_test_support"
path = "src/lib.rs"

[[bin]]
name = "count-test-dirs"
path = "src/bin/count-test-dirs.rs"

[dependencies]
log.workspace = true
sea-orm.workspace = true
stoneflow-storage = { path = "../storage", features = ["test-helpers"] }
tempfile.workspace = true
tokio.workspace = true
